# Site settings
title: Giacomo Vianello
email: giacomov@stanford.edu
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Giacomo Vianello. I talk about statistical methods for
  Astronomy/Astrophysics as well as data science topics.
 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://giacomov.github.io" # the base hostname & protocol for your site
github_username:  giacomov
linkedin_username: giacomovianello
permalink: /:title/ #/blog/:year/:month/:title.html
gems:
  - jekyll-sitemap
  - jekyll-feed
# Build settings
markdown: kramdown
mathjax: true
#theme: jekyll-theme-tactile
theme: minima
disqus:
  shortname: giacomov-github-io
google_analytics: UA-118662765-1
